# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rk3562-custom"
BBFILE_PATTERN_rk3562-custom = "^${LAYERDIR}/"
BBFILE_PRIORITY_rk3562-custom = "10"

LAYERDEPENDS_rk3562-custom = "core rockchip-updateimg qt5-layer meta-python"
LAYERSERIES_COMPAT_rk3562-custom = "scarthgap"

# Skip very large Qt modules not needed on embedded targets
BBMASK += "meta-qt5/recipes-qt/qt5/qtwebkit"
BBMASK += "meta-qt5/recipes-qt/qt5/qtwebengine"
